# GLOBAL CONFIGURATION

spring:
  application.name: service-three
  velocity.enabled: false

info.component: Service-Three

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  contextPath: /manage

server:
  contextPath: /
  port: 8086
---
# DOCKER CONFIGURATION
spring:
  profiles: docker
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        hostName: service-three
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckPath: ${management.contextPath}/health
        healthCheckInterval: 15s
